name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  check-package:
    name: Build & inspect
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hynek/build-and-inspect-python-package@v2

  test:
    name: Run quick tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: yezz123/setup-uv@v4

      - uses: wntrblm/nox@2024.04.15
        with:
          python-versions: "3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13"

      - name: Test Python 3.7
        run: nox -s tests -P 3.7

      - name: Test Python 3.8
        run: nox -s tests -P 3.8

      - name: Test Python 3.9
        run: nox -s tests -P 3.9

      - name: Test Python 3.10
        run: nox -s tests -P 3.10

      - name: Test Python 3.11
        run: nox -s tests -P 3.11

      - name: Test Python 3.12
        run: nox -s tests -P 3.13

      - name: Test Python 3.13
        run: nox -s tests -P 3.13
