#----------------------------------------------------------------------------------------------
# Copyright (c) The Einsums Developers. All rights reserved.
# Licensed under the MIT License. See LICENSE.txt in the project root for license information.
#----------------------------------------------------------------------------------------------

# find required packages
#
# The C++ API reference is generated by the in-tree libclang tool
# (apiary --emit-cpp-docs-json + render_cpp_rst.py); Doxygen and Breathe
# are no longer used, so Sphinx is the only documentation dependency.
if(EINSUMS_WITH_DOCUMENTATION)
  find_package(Sphinx)

  if(NOT Sphinx_FOUND)
    einsums_error(
      "Sphinx is unavailable, sphinx documentation generation disabled. Set Sphinx_ROOT to your sphinx-build installation directory."
    )
    set(EINSUMS_WITH_DOCUMENTATION OFF)
  endif()
endif()
