#----------------------------------------------------------------------------------------------
# Copyright (c) The Einsums Developers. All rights reserved.
# Licensed under the MIT License. See LICENSE.txt in the project root for license information.
#----------------------------------------------------------------------------------------------

set(EINSUMS_SET_OUTPUT_PATH ON)

if(MSVC)
  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE "${EINSUMS_WITH_BINARY_DIR}/Release/bin")
  set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE "${EINSUMS_WITH_BINARY_DIR}/Release/lib")
  set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${EINSUMS_WITH_BINARY_DIR}/Release/lib")
  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG "${EINSUMS_WITH_BINARY_DIR}/Debug/bin")
  set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG "${EINSUMS_WITH_BINARY_DIR}/Debug/lib")
  set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${EINSUMS_WITH_BINARY_DIR}/Debug/lib")
  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL "${EINSUMS_WITH_BINARY_DIR}/MinSizeRel/bin")
  set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_MINSIZEREL "${EINSUMS_WITH_BINARY_DIR}/MinSizeRel/lib")
  set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_MINSIZEREL "${EINSUMS_WITH_BINARY_DIR}/MinSizeRel/lib")
  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${EINSUMS_WITH_BINARY_DIR}/RelWithDebInfo/bin")
  set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO "${EINSUMS_WITH_BINARY_DIR}/RelWithDebInfo/lib")
  set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO "${EINSUMS_WITH_BINARY_DIR}/RelWithDebInfo/lib")
else()
  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${EINSUMS_WITH_BINARY_DIR}/bin")
  set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${EINSUMS_WITH_BINARY_DIR}/lib")
  set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${EINSUMS_WITH_BINARY_DIR}/lib")
endif()
