name: Run clang-format Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: 'src tests'
          extensions: 'h,hpp,c,cpp'
          clangFormatVersion: 14
          inplace: True
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions