name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: [ Release, Debug ]
        os: [ ubuntu-latest, macos-latest ]
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies - Ubuntu
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install -y liblapacke-dev liblapack-dev libblas-dev libhdf5-dev

    - name: Install Dependencies - macOS
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install hdf5 cmake zlib lapack
        echo "HDF5_ROOT=$(brew --prefix hdf5)" >> $GITHUB_ENV
        echo "LAPACKE_DIR=/home/linuxbrew/.linuxbrew/opt/lapack" >> $GITHUB_ENV

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DEINSUMS_SHOW_WARNING=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build/tests
      run: ./test-all
