name: CMake

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: [ Release, Debug ]
        os: [ ubuntu-latest, macos-latest ]
        hptt: [ HPTT=ON, HPTT=OFF ]
        include:
          - os: ubuntu-latest
            environment: linux-dev.yml
          - os: macos-latest
            environment: macos-dev.yml
    name: Build and Test
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: einsums-dev
          environment-file: devtools/conda-envs/${{matrix.environment}}
          miniforge-variant: Mambaforge
          use-mamba: true
          channels: conda-forge

      # Step is unnecessary; remove step for debugging.
      - name: Confound Environment - test fetched cblas/lapacke
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.build_type == 'Debug' && matrix.hptt == 'HPTT=OFF' }}
        run: |
          conda remove liblapacke libcblas

      - name: Configure CMake
        run: cmake -G Ninja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DEINSUMS_SHOW_WARNING=OFF -DEINSUMS_USE_${{matrix.hptt}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build/tests
        run: ./test-all
