name: CMake

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  #  Cancel a currently running workflow from the same PR or commit hash.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  detect_changes:
    name: "Detect Changes"
    uses: ./.github/workflows/detect-changes.yml

  linux_default:
    name: Linux
    needs: [ detect_changes ]
    if: ${{ contains(needs.detect_changes.outputs.filters, 'ci') || contains(needs.detect_changes.outputs.filters, 'src') }}
    uses: ./.github/workflows/linux-build-and-test.yml

  macos_default:
    name: macOS
    needs: [ detect_changes ]
    if: ${{ contains(needs.detect_changes.outputs.filters, 'ci') || contains(needs.detect_changes.outputs.filters, 'src') }}
    uses: ./.github/workflows/macos-build-and-test.yml

#  windows_default:
#    name: Windows
#    needs: [ detect_changes ]
#    if: ${{ contains(needs.detect_changes.outputs.filters, 'ci') || contains(needs.detect_changes.outputs.filters, 'src') }}
#    uses: ./.github/workflows/windows-build-and-test.yml