name: CMake

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: [ Release, Debug ]
        os: [ ubuntu-latest, macos-latest ]
        hptt: [ HPTT=ON, HPTT=OFF ]
        include:
          - os: ubuntu-latest
            environment: linux-dev.yml
          - os: macos-latest
            environment: macos-dev.yml
    name: Build and Test
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3

      - name: Write a Conda Env File
        run: |
          cat > export.yaml <<EOF
          name: einsums-dev
          channels:
            - conda-forge
            - nodefaults
          dependencies:
            - cmake
            - ninja
            - cxx-compiler
            - catch2
            - fftw
            - fmt
            - range-v3
            - blas-devel
            #MKL- libblas=*=*mkl
            #ACC- libblas=*=*accelerate
            #OBL- libblas=*=*openblas
            #OBL- openblas=*=*openmp*
            - liblapacke
            - hdf5
            - zlib
            - elfutils
          EOF
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            if [[ "${{ matrix.build_type }}" == "Release" ]]; then
              sed -i "s;#MKL;;g" export.yaml
            else
              sed -i "s;#OBL;;g" export.yaml
            fi
          fi
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            sed -E -i.bak "s;#OBL;;g" export.yaml
            sed -E -i.bak "s;- elfutils;;g" export.yaml
          fi
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            :
          fi
          # for empty bash block
          #   :
          # model sed for L/W
          #   sed -i "s;;;g" export.yaml
          # model sed for M
          #   sed -E -i.bak "s;;;g" export.yaml
          cat export.yaml

      - name: Install dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: einsums-dev
          #environment-file: devtools/conda-envs/${{matrix.environment}}
          environment-file: export.yaml
          miniforge-variant: Mambaforge
          use-mamba: true
          channels: conda-forge

      # Step is unnecessary; remove step for debugging.
      - name: Confound Environment - test fetched cblas/lapacke
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.build_type == 'Debug' && matrix.hptt == 'HPTT=OFF' }}
        run: |
          conda remove liblapacke libcblas --solver=libmamba

      - name: Conda environment
        run: |
          mamba info
          mamba list

      - name: Configure CMake
        run: cmake -G Ninja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DEINSUMS_SHOW_WARNING=OFF -DEINSUMS_USE_${{matrix.hptt}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Test (CTest)
        working-directory: ${{github.workspace}}/build
        run: ctest

      - name: Test (Catch2)
        if: false
        working-directory: ${{github.workspace}}/build/tests
        run: ./test-all
