name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: [ Release, Debug ]
        os: [ ubuntu-latest ]
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies - Ubuntu
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install -y liblapack-dev libblas-dev libhdf5-dev

    - name: Install Dependencies - macOS
      if: ${{ matrix.os == 'macos-latest' }}
      run: brew install hdf5 cmake

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build/tests
      run: ./test-all
