name: cpp-linter
permissions: read-all

on:
  push:
    branches: [ main ]
    paths-ignore: "doc"
  pull_request:
    branches: [ main ]
    paths-ignore: "doc"

jobs:
  cpp-linter:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install Dependencies - Ubuntu
      run: sudo apt-get install -y liblapacke-dev liblapack-dev libblas-dev libhdf5-dev

    - name: Configure CMake
      run: cmake -G Ninja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DEINSUMS_SHOW_WARNING=OFF

    - uses: cpp-linter/cpp-linter-action@v1
      id: linter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        version: 14
        style: file
        tidy-checks: ''
        database: 'build'
    - name: Fail fast?/
      if: steps.linter.outputs.checks-failed > 0
      run: |
        echo "Some files failed the linting checks!"