name: Documentation

on:
  push:
    branches:
      - main

jobs:
  # Build job
  build:
    defaults:
      run:
        shell: bash -el {0}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Write Conda Environment File
        run: |
          cat > export.yaml <<EOF
          name: docs-env
          channels:
            - conda-forge
            - nodefaults
          dependencies:
            - sphinx=6.2.1
            - pydata-sphinx-theme
            - doxygen
            - breathe
          EOF

      - name: Create Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: docs-env
          environment-file: export.yaml
          miniforge-variant: Mambaforge
          use-mamba: true
          channels: conda-forge

      - name: Conda Environment
        run: |
          mamba info
          mamba list

      - name: Build Documentation
        run: |
          cd docs
          make html

      - name: GitHub Pages Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: docs/_build/html
