name: Linux build and test workflow
on:
  workflow_call:
    inputs:
      build_ref:
        type: string
        required: false
      build_cache_suffix:
        type: string
        required: false
        default: "default"
      build_cache_size:
        type: string
        required: false
        default: 2G
      build_configure_extra_args:
        type: string
        required: false

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # compiler = default, implies the default compiler for the platform. for linux, this is gcc/g++
        compiler: [ default, intel ]
        blas: [ openblas, mkl ]
        build_type: [ RelWithDebInfo ]
        variant: [ default ]
        include:
          - compiler: intel
            blas: mkl
            build_type: RelWithDebInfo
            variant: lp64
            cmake_extra: >
              -DCMAKE_C_COMPILER=icx
              -DCMAKE_CXX_COMPILER=icpx
              -DMKL_INTERFACE=lp64
              -DCMAKE_CXX_FLAGS="--gcc-toolchain=${CONDA_PREFIX} --sysroot=${CONDA_PREFIX}/${HOST}/sysroot -target ${HOST}"
              -DOpenMP_CXX_INCLUDE_DIR="${CONDA_PREFIX}/include"
          - compiler: intel
            blas: mkl
            build_type: RelWithDebInfo
            variant: ilp64
            cmake_extra: >
              -DCMAKE_C_COMPILER=icx
              -DCMAKE_CXX_COMPILER=icpx
              -DMKL_INTERFACE=ilp64
              -DCMAKE_CXX_FLAGS="--gcc-toolchain=${CONDA_PREFIX} --sysroot=${CONDA_PREFIX}/${HOST}/sysroot -target ${HOST}"
              -DENABLE_EXTENDED_PRECISION=ON
        exclude:
          - compiler: intel
            blas: openblas

    name: "${{ matrix.compiler }} • ${{ matrix.blas }} • ${{ matrix.build_type }} • ${{ matrix.variant }}"
    runs-on: ubuntu-latest
    env:
      CCACHE_DIR: $GITHUB_WORKSPACE/build_cache_${{ inputs.build_cache_suffix }}
      CCACHE_MAXSIZE: ${{ inputs.build_cache_size }}
    defaults:
      run:
        shell: bash -el {0}
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.build_ref }}
          path: src

      - name: Cache Build Cache
        uses: actions/cache@v4
        with:
          path: build_cache_${{ inputs.build_cache_suffix }}
          key: einsums-${{ runner.os }}-${{ matrix.build_type }}-${{ inputs.build_cache_suffix }}-${{ matrix.compiler }}-${{ matrix.blas }}-${{ matrix.variant }}-${{ github.sha }}
          restore-keys: einsums-${{ runner.os }}-${{ matrix.build_type }}-${{ inputs.build_cache_suffix }}-${{ matrix.compiler }}-${{ matrix.blas }}-${{ matrix.variant }}-

      # From https://github.com/conda-incubator/setup-miniconda?tab=readme-ov-file#caching-environments
      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: einsums-env
          conda-remove-defaults: "true"

      - name: Install ruamel.yaml
        run: |
          conda install -c conda-forge ruamel.yaml

      - name: Merge Conda YAML files
        working-directory: src/devtools/conda-envs
        run: |
          pwd
          python merge_yml.py ${{ matrix.compiler }} ${{ matrix.blas }}

      - name: Get Date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Conda env
        uses: actions/cache@v4
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}-${{ runner.arch }}-${{ steps.get-date.outputs.today }}-${{ hashFiles('src/devtools/conda-envs/conda.yml') }}-${{ env.CACHE_NUMBER }}
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        id: cache

      - name: Update environment
        run: |
          pwd
          conda env update -n einsums-env -f src/devtools/conda-envs/conda.yml
          conda activate einsums-env
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Conda Environment
        run: |
          conda info
          conda list

      - name: Configure CMake
        run: |
          cmake \
            -G Ninja \
            -S "$GITHUB_WORKSPACE/src" \
            -B "$GITHUB_WORKSPACE/build" \
            -D EINSUMS_BUILD_PYTHON=ON \
            -D EINSUMS_WITH_COVERAGE=OFF \
            -D CMAKE_C_COMPILER_LAUNCHER=ccache \
            -D CMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -D EINSUMS_SHOW_WARNING=OFF \
            -D CMAKE_INSTALL_PREFIX="${{ github.workspace }}/installed" \
            -D CMAKE_PREFIX_PATH="${CONDA_PREFIX}" \
            ${{ matrix.cmake_extra }} ${{ inputs.build_configure_extra_args }}

      - name: Build and Install
        run: |
          cmake --build "${{ github.workspace }}/build" --config Release --target install

      - name: Test (CTest) - Unit Tests
        working-directory: "${{ github.workspace }}/build"
        run: ctest --rerun-failed --output-on-failure

      - name: Test (pytest) - unit tests
        working-directory: "${{github.workspace}}/installed"
        run: |
          if [[ "${{runner.os}}" == "Windows" ]]; then
            export PYTHONPATH="$PYTHONPATH;${{github.workspace}}/installed/lib;$CONDA_PREFIX/lib"
          else
            export PYTHONPATH=$PYTHONPATH:${{github.workspace}}/installed/lib:$CONDA_PREFIX/lib
          fi
          ls "${{github.workspace}}"
          pytest "${{github.workspace}}/tests" --cov="${{github.workspace}}/tests" --cov="${{github.workspace}}/einsums" --cov-report=xml

      - name: Generate coverage information
        if: ${{ contains(matrix.compiler, 'default') }}
        working-directory: "${{github.workspace}}/build"
        run: |
          export NOTES=$(find . -name "*.gcno")
          export SOURCES=${NOTES/.gcno/}
          echo "NOTES=$NOTES"
          echo "SOURCES=$SOURCES"
          gcov $SOURCES || echo "returned $?"
          lcov --capture --directory . --output-file coverage.info --exclude /usr/\* --exclude \*/_deps/\* --exclude \*/einsums-env/\*

      - name: Upload C++ coverage to Codecov
        if: ${{ contains(matrix.compiler, 'default') }}
        uses: codecov/codecov-action@v5
        with:
          directory: "${{github.workspace}}/build"
          working-directory: "${{github.workspace}}"
          disable_search: true
          files: ${{github.workspace}}/build/coverage.info
          flags: cpp
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Upload Python coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: "${{github.workspace}}"
          working-directory: "${{github.workspace}}"
          disable_search: true
          flags: python
          file: ${{github.workspace}}/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Test (find_package) - consume installation
        working-directory: "${{github.workspace}}/src/testing/consume"
        shell: bash -l {0}
        run: |
          cmake -S . \
            -B build \
            -G Ninja \
            --log-level verbose \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_PREFIX_PATH="${CONDA_PREFIX};${CONDA_PREFIX}/Library;${{ github.workspace }}/installed"
          cmake --build build
          ./build/HelloWorld
